# -*- coding: utf-8 -*-
"""_beatifulsoup_trendyol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ez9HQkOtPzFdbYgJ6r4o6Cj3NDiG7TE
"""

import requests
from bs4 import BeautifulSoup

url="https://www.trendyol.com/oyuncu-dizustu-bilgisayari-x-c106084"

headers={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
}

html = requests.get(url, headers=headers).content
soup = BeautifulSoup(html, "html.parser")

liste = soup.find_all("li", limit=5)

for li in liste:
    link = li.a
    if link is not None:
        link_href = link.get("href")
        if link_href is not None:
            print(link_href)
        else:
            print("Link href değeri bulunamadı.")
    else:
        print("Link bulunamadı.")