# -*- coding: utf-8 -*-
"""_beatifulsoup_example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a4y8jDQFoXApTdwFQdSPdaVVBBf9gnTU
"""

import requests
from bs4 import BeautifulSoup
url="https://www.imdb.com/chart/top/?ref_=nv_mv_250"
headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
}
html = requests.get(url, headers=headers).content
soup = BeautifulSoup(html, "html.parser")

liste = soup.find("ul", {"class":"ipc-metadata-list"}).find_all("li", limit=10)

for item in liste:
  filmadi = item.find("h3", {"class":"ipc-title__text"}).text
  puan = item.find("span", {"class":"ipc-rating-star"}).text
  print(f"{filmadi}, rating puanı= {puan}")