# -*- coding: utf-8 -*-
"""excence_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1outcjEepLhFZTsCJ__47QRB_jTD1UbmC
"""

import requests
import json

url = "https://api.exchangerate.host/lates"

bozulan_doviz = input("bozulan döviz türü: ")
alinan_doviz = input("alınan döviz türü: ")
miktar = int(input(f"ne kadar {bozulan_doviz} bozdurmak istiyorsunuz: "))

result = requests.get(url + bozulan_doviz)
result = json.loads(result.text)

print("1 {0} = {1} {2}".format(bozulan_doviz, result["rates"][alinan_doviz], alinan_doviz))
print("{0} {1} = {2}".format(miktar, bozulan_doviz, miktar*result["rates"][alinan_doviz], alinan_doviz))