# -*- coding: utf-8 -*-
"""film_arsiv_apisi.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-_Fbr4aZOy3Pn2CHwKswCKhvzhkdec0
"""

#themoviedb.org => film veya dizi arşivi
#themoviedb' nin sunduğu apiyi uygulamanızda kullanınız.
#anahtar kelimeye göre arama en popüler film listesi
#vizyondaki film listesi

import requests

class theMoviedb:
    def __init__(self):
        self.api_url = "https://api.themoviedb.org/3/"
        self.api_key = "1ea5da79463c75647a38ba73dad8c5c1"
        self.options1 = "search/keyword"

    def getPopulars(self):
        response = requests.get(f"{self.api_url}/movie/popular?api_key={self.api_key}&language=en-US&page=1")
        return response.json()

    def getSearch(self,keyword):
        response = requests.get(f"{self.api_url}/{self.options1}?api_key={self.api_key}&query={keyword}&page=1")
        return response.json()

movieApi = theMoviedb()

while True:             # siteye populer filmlerin listesi için get response talebi yapar ,
    secim = input("1- Popular Movies\n2- Search Movies\n3- Exit\nSeçim: ")

    if secim == "3":
        break
    else:
        if secim == "1":        # popular apisinden sonuçların içinden filmlerin adını çekerek ekrana yazdırır.
            movies = movieApi.getPopulars()
            for movie in movies['results']:
                print(movie['title'])
        if secim == "2":      # search apisinden içinde 'wailking' geçen filmleri arar ve sonuçların içinden filmleri çekerek adını ekrana yazdırır.
            keyword = input("keywords: ")
            movies = movieApi.getSearch(keyword)
            for movie in movies['results']:
                print(movie['name'])