# -*- coding: utf-8 -*-
"""github_rest_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HJWeUU9v1F9d9kiYFS0-sRQZfx5QEIUT
"""

import requests
import json


class Github:
  def __init__(self):
    self.api_url = 'https://api.github.com'

  def getUser(self, username):
    response =requests.get(self.api_url + '/users/' + username)
    return  response.json()

  def getRepositories(self, username):
    response= requests.get(self.api_url+'/users/' + username+ '/repos')
    return response.json()

  def createRepository(self, name):
   response = requests.post(self.api_url+'/user/repos?access_token='+ self.token, json={
        "name" : name,
        "description": "This is your first repository",
        "homepage":"https://fatmaakpunar.com",
        "private": False,
        "has_issues": True,
        "has_projects":True,
        "has_wiki":True
    })
   return response.json()

github = Github()

while True:
  secim = input('1- Find User\n2- Get Repositories\n3- Create Repository\n4- Exit\nSeçim: ')

  if secim =='4':
     break
  else:
    if secim =='1':
      username = input('username: ')
      result = github.getUser(username)
      print(f"name: {result['name']} public repos: {result['public_repos']} followers: {result['followers']}")
    elif secim =='2':
      username = input('username: ')
      result = github.getRepositories(username)
      for repo in result:
        print(repo['name'])
    elif secim =='3':
      name =input("repository name: ")
      result = github.createRepository(name)
      print(result)
    else:
      print('yanlış seçim')