message = "hello everyone. My name is Fatma"
#message = message.upper()
#message = message.title()
#message = message.lower()
#message = message.capitalize()
#message = message.strip()
#message = message.split()
#message = message.split('.')
#message = ' '.join(message)
#message = '*'.join(message)
#message = message.find('Fatma')
#message = message.replace('Fatma','merve')
#message = message.center(50)
#message = message.center(50,'*')
#isFound = message.startswith('h')
#isFound = message.endswith('a')
#print(isFound)
print(message)